services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: avrora
      POSTGRES_PASSWORD: avrora
      POSTGRES_DB: avrora
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://avrora:avrora@db:5432/avrora?schema=public
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - "3000:3000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:
